name: Build

on: [push]
jobs:
  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        mvn --batch-mode verify
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        mvn --batch-mode verify
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: |
        mvn --batch-mode verify
